export const CAFES = [
  {
    id: "ediya",
    title: "이디야 커피",
    titleEng: "EDIYA COFFEE",
    category: [
      {
        id: "beverage",
        code: "7",
        name: "음료",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "coffee", name: "COFFEE", code: "12" },
          { id: "beverage", name: "BEVERAGE", code: "13" },
          { id: "tea", name: "BLENDING TEA", code: "14" },
          { id: "flatccino", name: "FLATCCINO", code: "15" },
          { id: "shake", name: "SHAKE & ADE", code: "16" },
          { id: "bingsu", name: "ICE FLAKES", code: "71" },
          { id: "rtd", name: "RTD", code: "83" },
          { id: "ice-cream", name: "ICE CREAM", code: "154" },
          { id: "decaf", name: "DECAF", code: "155" },
          { id: "topping", name: "TOPPING", code: "159" },
        ],
      },
      {
        id: "food",
        code: "8",
        name: "푸드",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "bread", name: "BREAD", code: "17" },
          { id: "dessert", name: "DESSERT", code: "18" },
          { id: "deli", name: "DELI", code: "19" },
          { id: "rte", name: "RTE", code: "128" },
        ],
      },
    ],
  },
  {
    id: "mega-coffee",
    title: "메가MGC커피",
    titleEng: "MEGA MGC COFFEE",
    category: [
      {
        id: "beverage",
        code: "1",
        name: "음료",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "coffee", name: "커피", code: "1" },
          { id: "tea", name: "티", code: "2" },
          { id: "ade", name: "에이드&주스", code: "3" },
          { id: "smoothie", name: "스무디&프라페", code: "4" },
          { id: "decaf", name: "디카페인", code: "5" },
          { id: "beverage", name: "음료", code: "6" },
          { id: "new", name: "신상품", code: "9" },
        ],
      },
      {
        id: "food",
        code: "2",
        name: "푸드",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "dessert", name: "디저트", code: "7" },
          { id: "new", name: "신상품", code: "10" },
        ],
      },
    ],
  },
  {
    id: "compose-coffee",
    title: "컴포즈커피",
    titleEng: "Compose Coffee",
    category: [
      {
        id: "menu",
        code: null,
        name: "메뉴",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "combo", name: "컴포즈콤보", code: "207002" },
          { id: "season", name: "시즌한전", code: "192677" },
          { id: "coffee", name: "커피·더치", code: "185" },
          { id: "non-coffee", name: "논커피 라떼", code: "187" },
          { id: "smoothie", name: "프라페·스무디", code: "192" },
          { id: "shake", name: "밀크쉐이크", code: "193" },
          { id: "ade", name: "에이드·주스", code: "188" },
          { id: "ade", name: "티", code: "191" },
          { id: "dessert", name: "디저트", code: "339" },
        ],
      },
    ],
  },
  {
    id: "paiks-coffee",
    title: "빽다방",
    titleEng: "Paiks Coffee",
    category: [
      {
        id: "menu",
        code: null,
        name: "메뉴",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "new", name: "신메뉴", code: "menu_new" },
          { id: "coffee", name: "커피", code: "menu_coffee" },
          { id: "beverage", name: "음료", code: "menu_drink" },
          { id: "dessert", name: "아이스크림/디저트", code: "menu_dessert" },
          { id: "paiksccino", name: "빽스치노", code: "menu_ccino" },
        ],
      },
    ],
  },
  {
    id: "starbucks",
    title: "스타벅스",
    titleEng: "Starbucks",
    category: [
      {
        id: "beverage",
        code: null,
        name: "음료",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "cold-brew", name: "콜드 브루 커피", code: "W0000171.js" },
          { id: "brewed", name: "브루드 커피", code: "W0000060.js" },
          { id: "espresso", name: "에스프레소", code: "W0000003.js" },
          { id: "frapuccion", name: "프라푸치노", code: "W0000004.js" },
          { id: "blended", name: "블렌디드", code: "W0000005.js" },
          { id: "refresher", name: "스타벅스 리프레셔", code: "W0000422.js" },
          { id: "fizzio", name: "스타벅스 피지오", code: "W0000061.js" },
          { id: "tea", name: "티(티바나)", code: "W0000075.js" },
          { id: "etc", name: "기타 제조 음료", code: "W0000053.js" },
          { id: "rtd", name: "스타벅스 주스(병음료)", code: "W0000062.js" },
        ],
      },
      {
        id: "food",
        code: null,
        name: "푸드",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "bread", name: "브레드", code: "W0000013.js" },
          { id: "cake", name: "케이크", code: "W0000032.js" },
          { id: "sandwich", name: "샌드위치 & 샐러드", code: "W0000033.js" },
          { id: "warm", name: "따듯한 푸드", code: "W0000054.js" },
          { id: "fruit", name: "과일 & 요거트", code: "W0000055.js" },
          { id: "snack", name: "스낵 & 미니 디저트", code: "W0000056.js" },
          { id: "ice-cream", name: "아이스크림", code: "W0000064.js" },
        ],
      },
    ],
  },
  {
    id: "the-venti",
    title: "더 벤티",
    titleEng: "The Venti",
    category: [
      {
        id: "menu",
        code: null,
        name: "메뉴",
        sub: [
          { id: "all", name: "전체", code: null },
          { id: "new", name: "신메뉴", code: "1" },
          { id: "coffee", name: "커피", code: "2" },
          { id: "decaf", name: "디카페인", code: "3" },
          { id: "ice-blended", name: "아이스 블렌디드", code: "4" },
          { id: "juice", name: "주스/에이드", code: "5" },
          { id: "tea", name: "버블티/티", code: "6" },
          { id: "beverage", name: "베버리지", code: "7" },
          { id: "rtd", name: "사이드메뉴/RTD", code: "8" },
          { id: "pet", name: "반려동물", code: "9" },
        ],
      },
    ],
  },
];
